
stages:
  - checks
  - unit-tests

# let's make sure the source is formatted
clang-format:
  stage: checks
  script:
    - for bob in $(find src -type f) ; do echo ${bob} && diff ${bob} <(clang-format ${bob}) || exit ; done
#  only:
#    - merge-requests

# run the unit tests for asgard (gcc and clang)
catch2-gcc-tests:
  stage: unit-tests
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ ..
    - make -j 8
    - ctest -j 8
#  only:
#    - merge-requests

# run the unit tests for asgard (clang)
catch2-clang-tests:
  stage: unit-tests
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ ..
    - make -j 8
    - ctest -j 8

# run the unit tests for asgard (clang)
valgrind-check:
  stage: unit-tests
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ ..
    - make -j 8
    - valgrind --error-exitcode=1 ./asgard -p continuity_1 -n 2
    - valgrind --error-exitcode=1 ./asgard -p continuity_2 -n 2
    - valgrind --error-exitcode=1 ./asgard -p continuity_3 -n 2
    - valgrind --error-exitcode=1 ./asgard -p continuity_6 -n 2

#  only:
#    - merge-requests
